### ISSUE TITLE
kutugu - claimBySignature can double spend

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-06-tokensoft-judging#10]
kutugu

high

# claimBySignature can double spend

## Summary

There is no nonce limit on signatures, and when the beneficiary has votes again, the recipient can continue to double spend with the previous signature.

## Vulnerability Detail

```solidity
  function claimBySignature(
    address _recipient,
    uint32 _recipientDomain,
    address _beneficiary,
    uint32 _beneficiaryDomain,
    uint256 _total,
    bytes calldata _signature,
    bytes32[] calldata _proof
  ) external {
    // Recover the signature by beneficiary
    bytes32 _signed = keccak256(
      abi.encodePacked(_recipient, _recipientDomain, _beneficiary, _beneficiaryDomain, _total)
    );
    address recovered = _recoverSignature(_signed, _signature);
    require(recovered == _beneficiary, '!recovered');

    // Validate the claim
    _verifyMembership(_getLeaf(_beneficiary, _total, _beneficiaryDomain), _proof);
    uint256 claimedAmount = _executeClaim(_beneficiary, _total);

    _settleClaim(_beneficiary, _recipient, _recipientDomain, claimedAmount);
  }
```

There is no nonce for the signature, assuming that the beneficiary authorization recipient can claim A amounts and will burn A token.
After a period of time beneficiary has B token again, and B > A. In this case, the recipient can continue to claim with the previous signature.

## Impact

The recipient can double spend to claim, resulting in beneficiary's loss of funds.

## Code Snippet

- https://github.com/sherlock-audit/2023-06-tokensoft/blob/1f58ddb066ab383c416cfcbf95c9902683506e96/contracts/contracts/claim/abstract/CrosschainMerkleDistributor.sol#L129-L133

## Tool used

Manual Review

## Recommendation

Add a nonce to the signature

**Comment by 0xDE-GEN** [comment]
Escalate

I think this should be judged as medium. 
According to Sherlock docs, even if unlikely, it should be judged as medium if it is a possible scenario. Also, there is a loss of funds allocated to actual users, not a loss at the gas fee level.

> Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. The attack path is possible with assumptions that either mimic on-chain conditions or reflect conditions that have a reasonable chance of becoming true in the future. The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant). The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this should be judged as medium. 
> According to Sherlock docs, even if unlikely, it should be judged as medium if it is a possible scenario. Also, there is a loss of funds allocated to actual users, not a loss at the gas fee level.
> 
> > Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. The attack path is possible with assumptions that either mimic on-chain conditions or reflect conditions that have a reasonable chance of becoming true in the future. The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant). The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
It is definitely a borderline issue. 
Still would tend to low, as the user actually grants another user to claim all his airdrop tokens with that signature.

**Comment by akshaysrivastav** [comment]
One thing to notice here is that the `_total` parameter is validated against both the user signature and the merkle proof. It should be unlikely that a new `_total` value passes both the checks.

So when 
- B != A, user signature check will pass but merkle proof validation will fail.
- B == A, no tokens will be distributed.

**Comment by 0xDE-GEN** [comment]
The core problem with this issue is that it applies to all airdrop events, see my issue #203 for a different scenario.

1. in airdrop event 1, `UserA` is allocated `100 TokenA` and passes the signature to `UserB` to sell. 
2. in another airdrop event N, `UserA` is also allocated `100 TokenB`. 
3. `UserB` reuses the signature received in event 1 and takes `100 TokenB`.

The important point is that any token can replay its signature if it receives the same amount in any event.

Of course, it's unusual to receive the same amount, so I think this is a medium.
(This issue may need to be viewed as a separate issue as it does not present the scenario presented in #203)

**Comment by Shogoki** [comment]
> The core problem with this issue is that it applies to all airdrop events, see my issue #203 for a different scenario.
> 
> 1. in airdrop event 1, `UserA` is allocated `100 TokenA` and passes the signature to `UserB` to sell.
> 2. in another airdrop event N, `UserA` is also allocated `100 TokenB`.
> 3. `UserB` reuses the signature received in event 1 and takes `100 TokenB`.
> 
> The important point is that any token can replay its signature if it receives the same amount in any event.
> 
> Of course, it's unusual to receive the same amount, so I think this is a medium. (This issue may need to be viewed as a separate issue as it does not present the scenario presented in #203)

Yep would be problem in the unlikely event of the contract being reused for the airdrop of another token and the same address would be eligible for the exact same token amount.

It is somewhere between Medium & Low, personally still tend to low because of the unlikeliness.

**Comment by akshaysrivastav** [comment]
> Yep would be problem in the unlikely event of the contract being reused for the airdrop of another token

The [storage state](https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L81-L82) of Distributor contract is never reset and there is no way to reset that state even by admin access. So using the same Distributor contract for another token distribution will be a big mistake and can cause incorrect distribution or loss of tokens. 

Distributor is never meant to be reused.

**Comment by 0xDE-GEN** [comment]
Even if the contract is not reused, the vulnerability still exists.
The signature value is expressed as `abi.encodePacked(_recipient, _recipientDomain, _beneficiary, _beneficiaryDomain, _total)`, which contains no information about the contract. 
Therefore, once signed, the information will affect any future airdrops supported by tokensoft.
All that is required is to receive the same amount of airdrop.

**Comment by hrishibhat** [comment]
Result:
Low
Has Duplicates 
Reverting on the previous decision, agree with the Sponsor comment:
> I think this should be a low severity bug because the beneficiary is trying to send tokens to the recipient. In general, all of these distributors can be "double-spent" by any "attacker" but it's just sending tokens to where they are supposed to go anyway.

Unless someone makes the mistake of selling their signature don't see a way to manipulate this within the contracts causing loss of funds.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dot-pengun](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/10/#issuecomment-1667082011): rejected
