### ISSUE TITLE
pks_ - Uncorrect claimable token amounts and price tiers end time if L2 sequencer goes down

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#163]
pks_

medium

# Uncorrect claimable token amounts and price tiers end time if L2 sequencer goes down

## Summary

Related contracts will not work nomally when l2 sequencer goes down.

## Vulnerability Detail

In the current implementation, several contracts include `PriceTierVestingSale_2_0` and `Distributor` use `block.timestamp` to calculate claimable token amounts and price tiers end time.
However, it's vulnerable when l2 sequencer go down cause that `block.timestamp` is unusable. L2 chains like arbitrum and optimism upgrade their sequencer occasionally, such as the recent [optimism bedrock upgrade](https://cryptopotato.com/optimism-bedrock-upgrade-release-date-revealed/) cause the sequencer can't be able to process transactions for several hours. Or l2 sequencer bug could also cause transactions in stuck, such as [arbitrum sequencer bug](https://beincrypto.com/arbitrum-sequencer-bug-causes-temporary-transaction-pause/). So it's necessary to implement a mechanism to handle this issue in some abnormal conditions. 

## Impact

Several contracts that depend on `block.timestamp` will be not work nomally when l2 sequencer goes down.

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/PriceTierVestingSale_2_0.sol#L126-L129C14

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L116-L127

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/PriceTierVestingSale_2_0.sol#L54-L64

## Tool used

vscode, Manual Review

## Recommendation

Use chainlink [sequencer up feed](https://docs.chain.link/data-feeds/l2-sequencer-feeds), consider integrating the up-time feed and give the contract extra time to handle such an issue when l2 sequencer goes down.

Duplicate of #64

**Comment by Shogoki** [comment]
Escalate 
This is a duplicate of #64 and should be judged the same. It was excluded because of unclear scope definitions (see my comments on #64)

**Comment by sherlock-admin2** [comment]
> Escalate 
> This is a duplicate of #64 and should be judged the same. It was excluded because of unclear scope definitions (see my comments on #64)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Medium 
Duplicate of #64

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/163/#issuecomment-1669119254): accepted
