### ISSUE TITLE
mrvincere - Contract Funds Drain by Gas Fees on Failed Claim Transactions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#167]
mrvincere

high

# Contract Funds Drain by Gas Fees on Failed Claim Transactions

## Summary

Attackers can call ```claim()``` on addresses with 0 claimable tokens to force gas fees on contract leading to draining of funds because even when the claimable tokens are 0, the contract calls the ```token.safeTransfer()``` . This can result in Griefing attack against the contract.

## Vulnerability Detail

- claim() callable by any external caller
- Attacker can call claim(victimAddress)
- Even if victim has 0 claimable tokens, transaction is still processed
- Gas fees are still charged to the contract for the failed transaction
- This drains contract funds through gas costs

## Impact

Allows attackers to:
- Drain victim gas funds by issuing many failed claims
- Disrupt service by wasting gas

## Code Snippet

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/BasicDistributor.sol#L46C2-L51C3

### claim()
```solidity
        function claim(address beneficiary) external nonReentrant {
                // effects
                uint256 claimedAmount = super._executeClaim(beneficiary, records[beneficiary].total);
                // interactions
                super._settleClaim(beneficiary, claimedAmount);
        }
```
#### claim() function calls the ```_executeClaim``` function which calculates the ```claimableAmount``` as ```0```. So now ```claimedAmount``` = ```0```.
 
https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L66C3-L85C4

### _executeClaim()
```solidity
  function _executeClaim(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual returns (uint256) {
    uint120 totalAmount = uint120(_totalAmount);


    // effects
    if (records[beneficiary].total != totalAmount) {
      // re-initialize if the total has been updated
      _initializeDistributionRecord(beneficiary, totalAmount);
    }
    
    uint120 claimableAmount = uint120(getClaimableAmount(beneficiary));
    require(claimableAmount > 0, 'Distributor: no more tokens claimable right now');


    records[beneficiary].claimed += claimableAmount;
    claimed += claimableAmount;


    return claimableAmount;
  }
```

#### Now ```claim()``` calls the ``` _settleClaim``` with ```claimedAmount``` as ```0```.

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L93C3-L96C4

### _settleClaim()
```solidity
  function _settleClaim(address _recipient, uint256 _amount) internal virtual {
    token.safeTransfer(_recipient, _amount);
    emit Claim(_recipient, _amount);
  }
```

## Tool used

Manual Review

## Recommendation

- Check claimable amount first
- Revert early if 0 claimable tokens
- Consider gas price minimum

**Comment by MrViNC3R3** [comment]
Escalate

I don't understand why was this excluded.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I don't understand why was this excluded.
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
