### ISSUE TITLE
xAriextz - User can claim tokens without ERC20Votes being burned

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#171]
xAriextz

medium

# User can claim tokens without ERC20Votes being burned

## Summary
A malicious user can claim tokens in all contracts without having his ERC20Votes burned
## Vulnerability Detail
The amount of tokens to be burned is calculated as follows: return (tokenAmount * voteFactor) / fractionDenominator;
In the case where we have a low tokenAmount or a low voteFactor compared to fractionDenominator, this calculation will result in a 0, which will lead to 0 tokens being burned, even if tokenAmount was claimed. 

Example: when using the continous vesting, the tokens become claimable with time. Imagine we have a voteFactor=10 ** 17 and a fractionDenominator=10 ** 18. In case we call the claim() function each time 9 tokens are claimable, the calculation would be: (9 * 10 ** 17) / 10 ** 18, which will round to 0 in Solidity. This means that if a malicious user calls the claim() function each time that 9 tokens are claimable, we would get 0 ERC20Votes tokens burned each time, resulting in him claiming all the tokens but keeping his ERC20Votes over time.
## Impact
Medium: the user can conserve all his ERC20Votes while also claiming all his tokens. 
## Code Snippet
Burn function call: https://github.com/SoftDAO/contracts/blob/291df55ddb0dbf53c6ed4d5b7432db0c357ca4d3/contracts/claim/abstract/AdvancedDistributor.sol#L94
Where the amount of tokens to be burned is calculated:
https://github.com/SoftDAO/contracts/blob/291df55ddb0dbf53c6ed4d5b7432db0c357ca4d3/contracts/claim/abstract/AdvancedDistributor.sol#L73
## Tool used

Manual Review

## Recommendation
Round up this calculation. This will result in the end in more ERC20Votes tokens being burned from the user than possible, so you have to take into account this.

**Comment by jkoppel** [comment]
Escalate

This is not a duplicate of #56. #56 outlines how someone may become unable to withdraw if adjust() is called, and applies any time votingFactor is not a perfect multiple of fractionDenominator.

This report is for a separate issue which is at most a valid low. This report only shows that someone who claims tokens may wind up with a few extra voting tokens. It is insignificant unless votingFactor is set to a very small number.

#56 is a valid medium; this report is either invalid or a valid low.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is not a duplicate of #56. #56 outlines how someone may become unable to withdraw if adjust() is called, and applies any time votingFactor is not a perfect multiple of fractionDenominator.
> 
> This report is for a separate issue which is at most a valid low. This report only shows that someone who claims tokens may wind up with a few extra voting tokens. It is insignificant unless votingFactor is set to a very small number.
> 
> #56 is a valid medium; this report is either invalid or a valid low.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
> Escalate
> 
> This is not a duplicate of #56. #56 outlines how someone may become unable to withdraw if adjust() is called, and applies any time votingFactor is not a perfect multiple of fractionDenominator.
> 
> This report is for a separate issue which is at most a valid low. This report only shows that someone who claims tokens may wind up with a few extra voting tokens. It is insignificant unless votingFactor is set to a very small number.
> 
> #56 is a valid medium; this report is either invalid or a valid low.

Agree with escalation

**Comment by hrishibhat** [comment]
Result:
Low 
Unique
This is a valid low issue based on the escalation. The impact is not significant enough for a medium

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [jkoppel](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/171/#issuecomment-1667143103): accepted
