### ISSUE TITLE
AkshaySrivastav - `CrosschainMerkleDistributor.claimByMerkleProof` does not work for cross chain airdrops

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#189]
AkshaySrivastav

medium

# `CrosschainMerkleDistributor.claimByMerkleProof` does not work for cross chain airdrops

## Summary
`CrosschainMerkleDistributor.claimByMerkleProof` does not work for cross chain airdrops as it always uses `domain` parameter (domain of source chain) for merkle proof validation.

## Vulnerability Detail
The contest readme explicitly mentions [here](https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/README.md?plain=1#L16) that:
> The beneficiaries (i.e. those people that will receive tokens in the airdrop) can be either EOAs or smart contracts, and can claim tokens with a merkle proof (`crosschainTrancheVestingMerkle.claimByMerkleProof()`) - EOA and smart contract: must receive tokens on address and chain specified in the merkle leaf

A similar statement is present in code comments [here](https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/CrosschainMerkleDistributor.sol#L23) which states:
>  `claimByMerkleProof` allows any address to claim funds on behalf of a beneficiary to the Connext domain and address specified in the merkle leaf by providing a merkle proof

The above statements clearly says that if the merkle leaf specifies `ChainX` as domain then the `claimByMerkleProof` function must distribute those tokens to the recipient on `ChainX`.

However, the implementation of this function is different:
```solidity
  function claimByMerkleProof(
    address _beneficiary,
    uint256 _total,
    bytes32[] calldata _proof
  ) external {
    _verifyMembership(_getLeaf(_beneficiary, _total, domain), _proof);
    // effects
    uint256 claimedAmount = _executeClaim(_beneficiary, _total);

    // interactions
    _settleClaim(_beneficiary, _beneficiary, domain, claimedAmount);
  }
```
It can be seen that in the first statement of the function, it uses `domain` parameter for merkle proof validation. The `domain` parameter of `CrosschainMerkleDistributor` contract stores the domain of source chain (on which the Distributor contract is deployed).

In case the Distributor is deployed on Arbitrum and a recipient is set to receive tokens on Polygon, the `claimByMerkleProof` function will incorrectly use Arbitrum's domain to validate the merkle proof, this validation will surely fail because the actual merkle leaf was generated with Polygon's domain.

This incorrect mechanism will make the `claimByMerkleProof` function unusable by recipients who are set to receive the airdrop on a different chain.

## Impact
Explained above

## Code Snippet
https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/CrosschainMerkleDistributor.sol#L98

## Tool used

Manual Review

## Recommendation
Consider taking an input variable for domain and use that for merkle proof validation just like how it is done in `claimBySignature` function. 

Duplicate of #58

**Comment by akshaysrivastav** [comment]
This issue clearly demonstrate that due to an implementation bug the contracts won't be able to perform a crucial protocol operation that it always intended to perform.

Quick recap, the protocol wants to support cross chain claims of airdrop tokens but due to incorrect use of source chain `domain` the operation cannot be processed.

**Comment by Oot2k** [comment]
Escalate
Duplicate of 58

**Comment by sherlock-admin2** [comment]
> Escalate
> Duplicate of 58

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
Yes, it is a duplicate of #58.
Discussion about the issue should be continued on #58.

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #58 
The final validity of the issue will be decided based on the escalation resolution in #58

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Oot2k](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/189/#issuecomment-1670981366): accepted
