### ISSUE TITLE
josephdara - Random Number is always zero in the BasicDistributor

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#193]
josephdara

high

# Random Number is always zero in the BasicDistributor

## Summary
In the constructor of the BasicDistributor, a salt value of ``` uint160(uint256(blockhash(block.number - 1)))``` is passed which is used to set the randomValue, in the inheritted contracts. 
However if we check the inheritance, It gives this function
```solidity
  function _setPseudorandomValue(uint160 salt) internal {
    if (distancePerSecond == 0) {
      // there is no delay: random value is not needed
      return;
    }
    require(salt > 0, 'I demand more randomness');
    randomValue = uint160(uint256(blockhash(block.number - 1))) ^ salt;
  }
```
Here the salt is passed in and randomized again
```solidity

  require(salt > 0, 'I demand more randomness');
    randomValue = uint160(uint256(blockhash(block.number - 1))) ^ salt;
  }
```
Calculating this would always give a random num value of zero because
```solidity
uint160(uint256(blockhash(block.number - 1))) ^ uint160(uint256(blockhash(block.number - 1)))  = 0
```
## Impact
randomNumber is always zero, which it shouldnt be

## Code Snippet
https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/BasicDistributor.sol#L9-L16
## Tool used

Manual Review

## Recommendation
Do not use the same value for salt as is used to get a randomNumber

**Comment by Josephdara** [comment]
Escalate

Report was not reviewed

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Report was not reviewed

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Shogoki** [comment]
This was initially invalidated because of the scoping issues with this contest.

I think this is a bug, however i do not think it is a medium severity.
Can be a valid low.

**Comment by hrishibhat** [comment]
@Josephdara Do you have additional points to show the impact of this issue?

**Comment by Josephdara** [comment]
Thanks for the mention

The BasicDistributor Iis within scope. And the value here is being hardcoded into the constructor
This is not a low severity because the random value itself cannot be updated. Hence the value of zero initially computed would be the random value. No matter the block number

**Comment by hrishibhat** [comment]
@Josephdara 
Right so it is understood random value is not random but it still does not show the medium impact of using 0 as a random value.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue and the impact is not significant since there is no loss or core functionality breaking

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [josephdara](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/193/#issuecomment-1670301977): rejected
