### ISSUE TITLE
stopthecap - _getOraclePrice() doesn't check If Arbitrum sequencer is down in Chainlink feeds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#229]
stopthecap

medium

# _getOraclePrice() doesn't check If Arbitrum sequencer is down in Chainlink feeds

## Summary
When utilizing Chainlink in L2 chains like Arbitrum, it's important to ensure that the prices provided are not falsely perceived as fresh, even when the sequencer is down. 

## Vulnerability Detail
From [Chainlink documentation](https://docs.chain.link/data-feeds/l2-sequencer-feeds):
Optimistic rollup protocols have a sequencer that executes and rolls up the L2 transactions by batching multiple transactions into a single transaction.
If a sequencer becomes unavailable, it is impossible to access read/write APIs that consumers are using and applications on the L2 network will be down for most users.
This means that if the project does not check if the sequencer is down, it can return stale results.

Note that It is a different issue from checking oracle price freshness.
Because in the case of sharp price fluctuations, the price may be updated several times, although the final price is in freshness, but it may not be the latest price.
There's a similar [issue](https://solodit.xyz/issues/6689) here.

## Impact
Invalid or stale prices may be returned for the protocol

## Code Snippet
https://github.com/sherlock-audit/2023-06-tokensoft/blob/1f58ddb066ab383c416cfcbf95c9902683506e96/contracts/contracts/claim/abstract/PriceTierVesting.sol#L30-L45
## Tool used

Manual Review

## Recommendation
From [Chainlink documentation](https://docs.chain.link/data-feeds/l2-sequencer-feeds#example-code):    
```solidity
        (
            /*uint80 roundID*/,
            int256 answer,
            uint256 startedAt,
            /*uint256 updatedAt*/,
            /*uint80 answeredInRound*/
        ) = sequencerUptimeFeed.latestRoundData();

        // Answer == 0: Sequencer is up
        // Answer == 1: Sequencer is down
        bool isSequencerUp = answer == 0;
        if (!isSequencerUp) {
            revert SequencerDown();
        }

        // Make sure the grace period has passed after the
        // sequencer is back up.
        uint256 timeSinceUp = block.timestamp - startedAt;
        if (timeSinceUp <= GRACE_PERIOD_TIME) {
            revert GracePeriodNotOver();
        }

        // prettier-ignore
        (
            /*uint80 roundID*/,
            int data,
            /*uint startedAt*/,
            /*uint timeStamp*/,
            /*uint80 answeredInRound*/
        ) = dataFeed.latestRoundData();
```

Duplicate of #64

**Comment by Shogoki** [comment]
Escalate 
This is a duplicate of #64 and should be judged the same. It was excluded because of unclear scope definitions (see my comments on #64)

**Comment by sherlock-admin2** [comment]
> Escalate 
> This is a duplicate of #64 and should be judged the same. It was excluded because of unclear scope definitions (see my comments on #64)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Medium 
Duplicate of #64

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-06-tokensoft-judging/issues/229/#issuecomment-1669116817): accepted
