### ISSUE TITLE
mrvincere - Tokens Lost on Re-Purchase in BasicDistributor

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#33]
mrvincere

high

# Tokens Lost on Re-Purchase in BasicDistributor

## Summary

The ```BasicDistributor``` contract can lose track of previously purchased tokens when a beneficiary buys additional tokens due to improper handling of reinitialization. This results in the loss of rightfully purchased tokens.

## Vulnerability Detail

The BasicDistributor constructor calls _initializeDistributionRecord() to initialize each beneficiary's distribution record.

This function sets the total field to the passed _totalAmount without accumulating prior totals:

```solidity
function _initializeDistributionRecord(
  address beneficiary, 
  uint256 _totalAmount
) {

  uint120 totalAmount = uint120(_totalAmount);
  records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);

}
```
When a beneficiary purchases more tokens over time, the constructor is called multiple times, rewriting the total instead of summing.

## Impact

1.     Beneficiaries rightfully owed tokens from multiple purchases will have funds lost
2.     Significant financial impact depending on amount of tokens lost
3.     Negative user experience from losing funds
4.     Loss of trust in platform due to unmet expectations

### BasicDistributor.sol

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/BasicDistributor.sol#L9C2-L28C3
```solidity
        constructor(
                IERC20 _token, // the purchased token
                uint256 _total, // total claimable
                string memory _uri, // information on the sale (e.g. merkle proofs)
                uint256 _voteFactor, // voting power multiplier as fraction of fractionDenominator
                address[] memory _recipients,
                uint256[] memory _amounts
        ) AdvancedDistributor(_token, _total, _uri, _voteFactor, 10000, 0, uint160(uint256(blockhash(block.number - 1)))) {
                require(_recipients.length == _amounts.length, "_recipients, _amounts different lengths");
                uint256 _t;
                for (uint256 i = _recipients.length; i != 0; ) {
                        unchecked {
                                --i;
                        }


                        _initializeDistributionRecord(_recipients[i], _amounts[i]);
                        _t += _amounts[i];
                }
                require(_total == _t, "sum(_amounts) != _total");
        }
```

###  _initializeDistributionRecord()

https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L47C3-L59C4
```solidity
  function _initializeDistributionRecord(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual {
    uint120 totalAmount = uint120(_totalAmount);


    // Checks
    require(totalAmount <= type(uint120).max, 'Distributor: totalAmount > type(uint120).max');


    // Effects - note that the existing claimed quantity is re-used during re-initialization
    records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);
    emit InitializeDistributionRecord(beneficiary, totalAmount);
  }
```

## Tool used

Manual Review

**Comment by MrViNC3R3** [comment]
Escalate 


This should be a valid issue .

**Comment by sherlock-admin2** [comment]
> Escalate 
> 
> 
> This should be a valid issue .

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
