### ISSUE TITLE
Mohammadreza - Unsafe Casting

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-tokensoft-judging#89]
Mohammadreza

medium

# Unsafe Casting

## Summary
Possible uint overflowing from uint256 to uint120 inside _executeClaim function of Distributor abstract.

## Vulnerability Detail
There is a possibility of overflowing from uint256 to uint120 for _totalAmount of _executeClaim internal function in Distributor contract which can lead to initiate wrong amount value inside records[beneficiary] structure.

## Impact
https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L70
https://github.com/sherlock-audit/2023-06-tokensoft/blob/main/contracts/contracts/claim/abstract/Distributor.sol#L57-L58

The impact can be seen inside the code snippet as { //! <order> <comment> } comments.

## Code Snippet

Distributor.sol - line 70
```solidity
   function _executeClaim(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual returns (uint256) {
  
    //! 1 unsafe casting
    uint120 totalAmount = uint120(_totalAmount);

    // effects
    if (records[beneficiary].total != totalAmount) {
      // re-initialize if the total has been updated
      
      //! 2 wrong totalAmount passed for: _totalAmount > uint120 max
      _initializeDistributionRecord(beneficiary, totalAmount);
    }
    // rest of the code...
  }
```

Distributor.sol - line 57,58
```solidity
   function _initializeDistributionRecord(
    address beneficiary,
    uint256 _totalAmount
  ) internal virtual {
  
    //! 3 useless casting since casted before.
    uint120 totalAmount = uint120(_totalAmount);

    // Checks
    //! 4 still useless check
    require(totalAmount <= type(uint120).max, 'Distributor: totalAmount > type(uint120).max');

    // Effects - note that the existing claimed quantity is re-used during re-initialization
    //! 5 totalAmount has wrong value for totalAmount > uint120 max since casted before.
    records[beneficiary] = DistributionRecord(true, totalAmount, records[beneficiary].claimed);
    emit InitializeDistributionRecord(beneficiary, totalAmount);
  }
```

## Tool used
Manual Review

## Recommendation
Even if there are several check effects on off-chain proof creation for (amount or total or totalAmount) <= type(uint120).max, it would be a best practice to use the following code
```solidity
   require(total <= type(uint120).max);
```
inside claim initiators which are satellites here.

**Comment by itsLokacho** [comment]
@Shogoki @sherlock-admin

Actually it was my first audit on sherlock, and i have mentioned the issue which its unsafe casting and also i provided the code snippet with the vulnerabilities of `_initializeDistributionRecord` and `_executeClaim` but in another mean.
i think it would be valid since they can be seen.
And also since im not eligible for the escalation, i had a request
if its possible, i dont want any reward from this issue if it gets valid
i just wanna to have a better issue ratio on sherlock.
thanks
